### ISSUE TITLE
Image section

### ISSUE THREAD

**Issue by anderl1** [aggrosoft/shopware-twig-load-cms-blocks#2]
hello, i use the plugin, but the output of a media section in cms pag daos not work. 
is this a problem of me?

**Comment by kingschnulli** [comment]
What exactly does not show and what is contained in that section? How do you include the snippet?

**Comment by anderl1** [comment]
hi, thanks for you rapide reaction. if have a cms page with two blocks, one image und one text block. only the text block is shown. 

            {{ cms(config('TkhCleverReachForm.config.cmsIdWelcome'), context)|sw_sanitize }}

This is my template snippet!

**Comment by kingschnulli** [comment]
Ah well, do not use sw_sanitize you must use raw in most configurations:

`{{ cms(config('TkhCleverReachForm.config.cmsIdWelcome'), context)|raw }}`

**Comment by anderl1** [comment]
i tried both!

```
<div class="cms-element-image">                                                      
<div class="cms-image-container is-cover" style="min-height:340px;">                  
</div>
</div>
```
the image container ist completly empty

sw_thumbnail have the media entity, but no html putput, the template is integratet in a own page no category or landuíng page, it seems this is my problem?

**Comment by kingschnulli** [comment]
Which shopware version are you using?
So you just have a simple landing page type cms page with just an image widget correct?

**Comment by anderl1** [comment]
I have a own route about controller and in template cms + form +cms

Template newsletter-confirmation.html.twig

```
{% sw_extends '@Storefront/storefront/base.html.twig' %}
    {% set formAction = path('frontend.subscribe.confirmation') %}

    {% block base_main_inner %}
    <div class="container-main">
        <div class="cms-page">

            {{ cms(config('TkhCleverReachForm.config.cmsIdWelcome'), context)|raw }}

            <div class="cms-section tkh-newsletter-subscribe-form-wrapper">
                <div class="cms-section-default boxed">

                    {{ 'newsletter.subscribe.emailText' | trans({'%mail%': data.get('mail')}) | raw }}

                    <form action="{{ formAction }}" method="post">
```

Route

   ```
/**
     * @Route("/subscribe-confirmation", name="frontend.subscribe.confirmation", methods={"POST","GET"})
     *
     * @param Request             $request
     * @param RequestDataBag      $data
     * @param SalesChannelContext $context
     *
     * @return Response
     * @throws \GuzzleHttp\Exception\GuzzleException
     *
     */
    public function showSubscribeConfirmation(Request $request, RequestDataBag $data, SalesChannelContext $context) : Response {

        $page = $this->formPageLoader->load($request, $context);

// some code for formular data

        return $this->renderStorefront('@storefront/storefront/page/cleverreach/newsletter-confirmation.html.twig', [
            'page'  => $page,
            'data'  => $data
        ]);
    }

```

**Comment by kingschnulli** [comment]
This sounds more like your page loader is not a navigation page loader - is this a custom page loader? Does the image show up if you just put that piece of code somewhere on your product detail page template?

**Comment by anderl1** [comment]
Sorry, i changed the wrong template. 

{{ cms(config('TkhCleverReachForm.config.cmsIdWelcome'), context)|raw }}

Now with filter "raw" it works!

Thank you very much!
